### ISSUE TITLE
[New NIP]: Incentivize stakers to vote

### ISSUE THREAD

**Issue by Cesnili-Kanka** [NeblioTeam/Neblio-Improvement-Proposals#11]
### Proposal Description

Brief:
A rewards system should be created to attract more voters from those that stake for Neblio Improvement Proposals. Each voter who engages with the process shall be rewarded with NEBL coins at 1% of their voting weight. To mitigate against yield chasers a solution to either have a secret snapshot 1-2 weeks before a vote is announced can be made or when the user votes, a look-back is executed for the wallet balance within the particular date range.

Side benefit:
This further opens the door for exchange platforms to gain interest adopting the NEBL token, allowing users to stake in a custodial setting without having to implement a personal NEBL wallet, and the exchange platform to allocate and raise liquidity via harvested vote rewards.

Method of dispersal:
The staker's coin balance as of snapshot or lookback date will the multiplied by 0.01 and that amount will locked until the end of the voting period. Upon vote completion the coins will be released to the voter's address either by automated means or through a web app claim and transfer contract.

Protecting against frivolous proposals:
Neblio team and developers retains at their discretion to invalidate a proposal before the voting period.

Why 1% per vote proposal?:
This is to stay relevant and competitive within the PoS ecosphere when comparing to interest rates and fiat currencies. 1% per staker vote on top of the base rate of 10% will make Neblio a great target for blockchain hobbyists wanting to be involved in  Neblio's use cases. 

Considerations:
More than 10 votes in a year could be a major boon to stakers but devalue existing non-staker's coins. This is expected and as the Neblio project matures it is likely there will be fewer proposals in the years following implementation of incentivized voting, making this engagement measure to be less utilized. Without an incentive system in place, voting will become more difficult to reach the minimum thresholds as the blockchain increases and cold holders disinterested only to hodl without input towards improvement.

### Proposal Voting Details

No particular block voting range is desired at this time, Neblio Team can decide the time duration and point which voting happens for optimal turnout if they believe this proposal is beneficial to the Neblio community.

### Other Information

For proposer contact pertaining to this initiative, reach out to @Cesnili_Kanka publicly within the Neblio community Telegram. Unsolicited direct messages will be treated as malicious by intention.

**Comment by MarkSamson** [comment]
I really like the idea. But I think that 1% gives a way to high inflation. In the proposal an example of 10 proposals per year is mentioned. If that would happen that would mean that the coin has an inflation of up to 20% in one year. I don't think that is way too much. Especially because there is also a possibility that there are more then 10 proposal.

As mentioned I like the idea but I think it should be done different to tackle the high inflation. Maybe something with only receiving the full 10% staking reward if you also vote for every proposal. Although that makes it also less interesting to start staking.

**Comment by NeblioTeam** [comment]
Thanks for writing another detailed proposal (hopefully GitHub will stop deleting them!). 

Due to the way block voting works in the code, it may be difficult for us to base staking rewards on whether a staker votes. However, it's not impossible, and if it is something the community votes for it's something we can add tot he roadmap and work on. 

Opening up for discussion to gather feedback.

**Comment by TheQuantumPhysicist** [comment]
Unfortunately, I don't ever see this happening because this is not enforceable in a secure and unbiased way. First, the vote provided by the user is not a consensus parameter that can be checked (meaning, the blockchain is useful for verifying identity and authenticity, not for verification). Leading to the second point, how hard is it to "vote anything" just to get more money? I can easily see this leading to spamming any vote just to get the extra 1%. In fact, *every* user can vote anything by putting one infinitely large entry in the voting table, leading to everyone getting the extra 1%, except for those who don't know about this "hack".

"Hey buddy, you wanna get an extra 1%? Just go to the console of neblio and paste this command, and enjoy the extra money".

If I'm missing something, please go ahead and tell me. But I have to say, it doesn't look good.

**Comment by Shane-Neblio** [comment]
I like the idea of incentive's but i'd rather not make the inflation anymore than it already is. 10% is fine as is.

I think a better approach would be to simply make it insanely EASY to vote that nodes would do it simply because it took no effort.

1. It's gotta be as simple
2. It's gotta be in their face.
3. it's gotta be done in a mere click of the mouse.
4. it should look appealing.. stand out. a dedicated icon.
5. maybe have it done via Tokens instead of typing in data. 

Have a button tab that says "Governance". In it it should show a list of all the nips it retrieves.. 
Beside each NIP should be a Vote button. You click it and 3 tokens are displayed. Yes token, No token, Abstain token
When you select one, then click "Confirm" & it will purchase that token as if it's a store-front & will deposit it to your address with the Metadata of the NIP associated with it written to the token automatically... stamped into it. Then you have only to leave this token in your wallet address during the voting session. 

You just pay the gas fee, but doesn't affect your staking. 

that's about the best i can come up with.

i think people would do it because it would be more Obvious & only requires a few mouse clicks.. no need to paste data in from elsewhere to fill in forms, which is why i think a bunch didn't bother.

**Comment by NeblioTeam** [comment]
Thanks to @TheQuantumPhysicist for correcting me and showing that this is not possible to implement securely, due to votes not being part of the consensus of the network. For that reason we must close this NIP. 

Personally, I believe being able to shape the Neblio network roadmap and being an **active** participant in the decisions of the network should be incentive enough for all stakers to want to vote on most NIPs.
