### ISSUE TITLE
[New NIP]: Add Exchanges that list NEBL on the Neblio Website

### ISSUE THREAD

**Issue by Jake2270** [NeblioTeam/Neblio-Improvement-Proposals#13]
### Proposal Description

Hi again team and community, as the title of this NIP states, would it be possible to add the exchanges that have NEBL listed, to the Neblio website? Have seen  some are there but have found NEBL to be on others like swap exchanges which should also be mentioned. 

I think it would be good for new people who find Neblio via the website, knowing exactly what exchanges have NEBL listed and updated as more exchanges add NEBL pairs. 

### Proposal Voting Details

1 week of voting in equivalent blocks

### Other Information

N/A

**Comment by NeblioTeam** [comment]
This is something our team has had a lot of discussion on internally over the years. When our redesigned website was created and launched, the web designers added a section that listed all the places NEBL was traded, but we ended up removing that section after some users in the community complained of selective scamming (blocking withdrawals) by HitBTC. 

The issue here is scams/exchange problems. NEBL is traded on a lot of small exchanges and swap exchanges that our team may have never had contact with at all. If we promote those exchanges in any way, such as by listing them on our official site, and then that exchange scams users, or has problems with withdrawals, etc, we are often blamed. 

There is a list of places where you can buy and sell NEBL that is maintained by the community and frequently posted in telegram and discord. Many of the exchanges on that list have never contacted us, nor do we know if they are trustworthy. We could certainly post the well-known trustworthy exchanges like Binance, but then we will get constant emails from the smaller exchanges asking to be added to the list, without any way for us to know if these exchanges are safe to promote.

For that reason we regretfully must deny this NIP. Perhaps this is something that is more suited for someone in the community to create and maintain. A simple website that has an up to date list of trustworthy exchanges, I bet the neblio.exchange domain name is even available.
