### ISSUE TITLE
[NIP22]: Neblio 2.0 Release

### ISSUE THREAD

**Issue by NeblioTeam** [NeblioTeam/Neblio-Improvement-Proposals#22]
### Proposal Description

Proposal by the Neblio Core Dev Team to release Neblio 2.0: a multipurpose hard fork of Neblio to upgrade it, featuring a new staking rewarding system, burn system of transaction fees, and a new economic model including a redenomination plan.

### Proposal Voting Details

Neblio was conceived in 2017, as a distributed, high performance blockchain platform built for enterprise and industry 4.0 applications and services.

We propose a quantum leap for Neblio to become Neblio 2.0 in this NIP in the most ambitious proposal made to date:

### Funding and Staking rewards system

The crypto scene has evolved considerably since Neblio was born: the current market is populated with some other great blockchain platforms for dApps focusing rather on a general audience for a greater adoption among the crypto community, leaving aside the consulting angle where Neblio was pricing and providing these services to enterprises in its former days; we do consider this model to be obsolete for the aforementioned reasons, and this is the reason why our ultimate goal is to work on the development of smart contracts and ease the development on Neblio.

The economic model of Nebl is likewise 6 years old, and it has not changed ever since, while everything in crypto has made a breakthrough: from ICOs to IDOs, IEOs, the boom of the NFTs, swaps on ERC20 and BEP20 tokens, rebrandings, etc.

The ambitious [Roadmap presented during the present Q3 2022](https://medium.com/neblio-blog/neblio-roadmap-2022-q2-2023-8a5cfb2f39c7) entails many milestones such as running a bug bounty program, listings of $NEBL in new exchanges, and, most importantly, our plan to develop an ecosystem fund so as to reward those developing dApps on Neblio, which require the existence of a community treasury.

The community treasury would only be used whenever there is a majority in the consensus of the voting via NIPs.
On the other hand, we should strengthen the PoS network by having more stakers and users running nodes, which can be achieved by offering more competitive staking rewards.

Actually, one of the requests that has been enquired many times in the past has been the addition of a new staking rewarding system to make it dynamic so node operators can determine whether they take fees or not, or even making it dynamic so those in the pools can determine the fees to be rewarded.

Hence, to achieve it all, our proposal is that the current staking reward system goes from 10% to the staker to 20% broken down as follows: 12% as a staking reward (dynamic) + 8% to the treasury fund. We, for one, believe that the 2% inflation generated towards the staker would be offset by those new users staking as well as by both the active initiatives led by our team and the community since the funds of the treasury would be released only upon voting approval.

### Wallets, burns and development

We have recently found out that the The Furnace - Burn Address wallet of Neblio since its inception, NXsZ1sAz2uHGxYK2rpXRhNfDnHa1NxRy1r, holding ≈112509067 NEBL and a manifold of NTP1 tokens at present, was operated back in August 2017, where some coins were moved outside the wallet. The information we have is that the private keys of this wallet were destroyed at an unspecified time ago without further proof of this fact from the previous owners.

We consider this may pose a big risk in case the private key is still available anywhere so it could be accessed either intentionally or unintentionally by any third-party, since this wallet holds over 5.78 times the current total supply of Neblio.

In this proposal, we are willing to consult our community to fork Neblio as well so these coins would be transferred to a new address, and thereafter, most of these coins will be transferred to a legit burn address without any private key generated at fork time, thus ensuring it is a real dead address for transparency of our community.

On the other hand it’s worth noting that the new team of Neblio, which includes 6 experienced full-time blockchain developers and many other marketers, acquired the rights of the project but did not receive any coins with the deal. All the blockchain and marketing professionals on Neblio are being run at the sole expense of the new team members. Hence we shall enable an allocation for the new team members in this new Neblio 2.0.

**Break down of the distribution of the current Furnace:**

1. New Burn Address: 102509067 coins
2. Ecosystem treasury: 4,000,000 $NEBL to allocate in emerging projects, bounties, adoption, listings and any other proposals, to be used only via approval of NIP
3. Team: 4,000,000 $NEBL - 20% at Fork time, 80% to be linearly vested for 20 months
4. Marketing: 1,000,000 $NEBL - For futures plans on marketing
5. Reserves: 1,000,000 $NEBL - To keep as contingency and burns

The Neblio team will upgrade Neblio to Neblio 2.0 in order to enable the ability to automatically burn TXs fees, using the same mechanism of Ethereum.

Moreover, we commit ourselves to propose regular NIPs every quarter to conduct periodic burnings of the new supply.

### Neblio 1:10 Redenomination plan
As part of the upgrade of Neblio to 2.0, and in order to benefit from unit bias amongst others, Neblio would like to consult our community via this NIP to implement a redenomination plan of the $NEBL coin.

The total supply of NEBL will be increased by 10:1, while the price will be scaled down by 1:10.

Hence 1:10 stands for 1 legacy $NEBL equals 10 upgraded $NEBL.

After the Neblio legacy to Neblio 2.0 upgrade, the balance of all the NEBL holders will be scaled in the same ratio accordingly.
Note that the ticker $NEBL will be preserved.

### Other Information

In case of approval of the present proposal, our core team will start the development of the aforementioned features and after completion, a hard fork will be performed on Neblio enabling them. We will enquire to update the nodes to our community as well as to exchanges in order to support the hard fork as well as the redenomination plan.

Start Block: 4365451
End Block: 4385611

**Comment by rickhenri** [comment]
Bad idea

**Comment by reinvl** [comment]
Terrible idea, I will vote against it.

**Comment by chiolivet** [comment]
Worst idea from the team ever

**Comment by chiolivet** [comment]
The team has been rolling out various good news but this one is simply a terrible idea and I am definitely voting against it

**Comment by Darrencheny** [comment]
Good idea，make a fresh start

**Comment by IWantMoreDecred** [comment]
I will vote against anything that increases the supply of neblio. I'm in it because it's a LOW supply coin. lower than bitcoin. That's what i like about it. Investors will bail if it increases. worst possible thing you could do to kill the chain.

What people want to see is supply go DOWN. not up. Our 10% inflation is already something some people complain about but gotta pay nodes, so a burn added in can help battle that. We don't need higher stake rewards. 10% is the sweet spot.  
This attracts investors, yet people want scarcity too! 

And do not touch that furnace. For all we know you could be trying to steal from it. We don't know you. What we do know is that it hasn't been accessed yet. It would have long ago if old team had private key to it. so no. I trust it's burned.  Any access or change to the furnace will have us all bail on this chain. 

If you guys really had VC money you'd not need a treasury. treasury was only suggested before because our previous team was too poor.  

No allocation acceptable. No increase in supply. buy the token like everyone else. 
If you believe in your abilities then that would be profitable to you. 

Should have done that just before you announced neblio had a new team. and staked it to earn 10% to pay for your time. you would have multiplied your money & took some off the market to drive up scarcity more. 

The only good thing in this proposal is the burn mechanism being like ethereum. Other than that I hate everything else about this proposal. Not good for community too. It would appear to be a red flag to investors. One thing investors really HATE is when they see a team awards themselves free tokens. 
Neblio will become a dead chain, i assure you, with these changes.


also note.. The original Neblio team never awarded themselves team tokens. The old Team-address was made up of tokens they BOUGHT with their OWN MONEY in the beginning. They never gave themselves any freebies. this says a lot for them. So this is also why i trust the furnace has no private key. if they say there is no private key, then there is none. That is to never be touched. But what i do not trust is you. This whole proposal looks scammy, and, as such, I would never trust a new furnace address.

**Comment by IWantMoreDecred** [comment]
I'll tell you the main thing holding Neblio back.  NUMBER 1 thing.

It has NO web connector to communicate with 3rd party websites. This is why DEFI has ignored it and even gaming.. web-app gaming that is. 

Terra Luna has Terra Station, located here
https://station.terra.money/ for governance and staking, but how do you connect to it? Via browser Extension, of course!
The "Terra Station Wallet" connector extension.

That can be found here, if you wish to view it:  https://chrome.google.com/webstore/detail/terra-station-wallet/aiifbnbfobpmeekipheeijimdpnlpgpp

Basically, if you make Neblio borrow ideas from Terra Station's layout and it's Terra Station Wallet... you could make our ORION web wallet have added governance/Staking delegation tabs like Terra Station does. 

Orion is a wallet itself, which is good, but, it cannot communicate with 3rd party websites for their defi and gaming because it is a website and not an extension. 

So i suggest ALSO developing a web extension wallet as well. Then give a Stake delegation and governance Tab to Orion.. and also squeeze into it a "Connect" button so Orion can ALSO connect to this web extension to communicate to see coin's located on that wallet too. 
Then this way Orion is not just a Wallet but ALSO can interact with other Connector-extension wallets to do stake/governance stuff.. and perhaps even buy/selling tokens via a DEX tab, if you're really ambitious, for the tokens within the NEBL ecosystem. 

All the big name coins are doing this.  Cardano has Yoroi and others.. Ethereum has Metamask and others... Terra Luna & Luna Classic have Terra Station Wallet..  Solana has also one [but forget it's name].

Any chains that never developed one have lost rank.. because 3rd parties who want to do web stuff have no clue how to interact with those chains.. So this is crucial.

This is the thing that can make or break Neblio and I firmly believe that this is the number 1 reason Neblio has gone from a top 50 coin to rank 1000, when it was at it's lowest.

You can read my old proposal here about NeblioMask.. but other names could be just as cool, like "Neblio Station" "Neblio Connect". 

https://github.com/NeblioTeam/Neblio-Improvement-Proposals/issues/7

**Comment by modrewrite** [comment]
@Shane-Neblio As a Neblio holder from the first hour, I completely agree with both of your comments!

**Comment by IWantMoreDecred** [comment]
[https://github.com/NeblioTeam/Neblio-Improvement-Proposals/issues/23](url)
